name:                   Type-Check

on:                     [push, pull_request]

jobs:
  mypy:
    runs-on:            ubuntu-latest
    name:               Mypy
    strategy:
      matrix:
        python-version:      [3.7, 3.8, 3.9, '3.10', '3.11']
    steps:
    - uses:             actions/checkout@v3
    - name:             Set up Python ${{ matrix.python-version }}
      uses:             actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name:             Install Dependencies
      run:              |
        pip install mypy
    - name:             mypy ${{ matrix.python-version }}
      run:              |
        mypy --install-types --non-interactive src/
